### ISSUE TITLE
Use Dailer.SetKeepAliveConfig on go1.23+

### ISSUE THREAD

**Issue by ignoramous** [celzero/firestack#33]
Why? https://github.com/golang/go/issues/48622 / https://github.com/tailscale/tailscale/issues/3363

Ref: https://github.com/golang/go/issues/62254

**Comment by Lanius-collaris** [comment]
I'd like to use syscall first if I can test before v055o (I don't know the release date) 🤗.

**Comment by ignoramous** [comment]
> I'd like to use syscall first 

You could, but isn't go1.23 only a week or two away...
