### ISSUE TITLE
ParseAddr: invalid ip

### ISSUE THREAD

**Issue by hussainmohd-a** [celzero/firestack#38]
`ipmap.go:255: W ipmap: seed: invalid ipstr [::1]: err1 ParseAddr("[::1]"): each colon-separated field must have at least one digit (at "[::1]") / err2 missing ]`

**Comment by hussainmohd-a** [comment]
`ipmap.go:255: W ipmap: seed: invalid ipstr localhost: err1 ParseAddr("localhost"): unable to parse IP / err2 not an ip:port`

**Comment by ignoramous** [comment]
https://github.com/celzero/firestack/commit/babfc05b4af460df914e0222e2706d387d729683

https://github.com/celzero/firestack/commit/aef4bb74186e858a32a99df78f7c6526dc1e254f

https://github.com/celzero/firestack/commit/b9dd9dffccc4fa147e694eec0ba6d4c48e7ef7d8
